# Generated by Django 6.0.4 on 2026-05-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Closed Deal', 'verbose_name_plural': 'Closed Deals'},
        ),
    ]
