# Generated by Django 6.0.3 on 2026-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contact_options_alter_deal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(choices=[('us', 'US'), ('sa', 'SA')], default='us', max_length=5),
        ),
    ]
